import React, { ReactElement, Fragment } from "react";
import styled from "styled-components";
import Head from "next/head";
import Button from "@mui/material/Button";
import Stack from "@mui/material/Stack";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";

const BckImg = styled.div`
  height: 100vh;
  position: relative;
  width: 100%;
  overflow: hidden;
  background-size: cover;
  background-image: linear-gradient(90deg, #ffffff, #add8e6 );
  margin: -8px;
  min-height: 100%;
`;
const HeroText = styled(Typography)`
  margin-top: 20;
  text-shadow: 0 4px 4px rgb(0 0 0 / 25%);
  background: -webkit-linear-gradient(#0000FF, #1976d2);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  font-weight: 500;
`;

const NewTabLink = styled.a`
  text-decoration: none;
`;


function LandingPage(): ReactElement {
  return (
    <Fragment>
      <Head>
        <title>PrivacyProtocol</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BckImg>
        <Box
          sx={{
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
            paddingTop: 40
          }}
        >
          <HeroText variant="h1" gutterBottom align="center">
            The Privacy Protocol
          </HeroText>
          <Stack direction="row" spacing={4} sx={{ flexGrow: 20 }}>
            <NewTabLink href="http://localhost:3000/register" target="_blank">
              <Button size="large" variant="contained">
                Enter App
              </Button>
            </NewTabLink>
            <NewTabLink href="http://localhost:3000/register" target="_blank">
              <Button size="large" variant="contained">
                Documentation
              </Button>
            </NewTabLink>
          </Stack>
        </Box>
      </BckImg>
    </Fragment>
  );
}

export default LandingPage;
